name: Auto Deploy Frontend [main]

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy React Frontend on Self-Hosted Debian 12
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: .env settings
        run: echo "REACT_APP_VITE_API_URL=${{ secrets.REACT_APP_VITE_API_URL }}" > .env
        
      - name: Build and Restart
        run: |
            cd /home/bin/cloakbox_front
            git pull origin main

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            nvm install 20.19.3
            nvm use 20.19.3

            npm ci
            npm run build

            sudo systemctl restart cloakbox_front
